# Generated by Django 4.2.5 on 2025-04-20 07:21

from django.db import migrations, models
import django.utils.timezone
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortCode', models.CharField(default=shortener.models.generate_shortcode, max_length=10, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accessCount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
